#create a bsic github action to use the github action Mukund-Tandon/Hashnode-Blog-Manger/.github/workflows/main.yaml

name: "Hashnode Blog Manager test"
on:
  push:
    branches:
      - main

jobs:
    # dostuff:
    #   runs-on: ubuntu-latest

    #   steps:
    #       - name: Run Hashnode Blog Manager
    #         uses: Mukund-Tandon/Hashnode-Blog-Manger@main
    #         with:
    #           blog_path: "blogs"
    #           hashnode_access_token: ${{ secrets.HASHNODE_TOKEN }}

    fetch-secret-key:
                runs-on: ubuntu-latest
            
                steps:
                - name: Checkout code
                  uses: actions/checkout@v2
            
                - name: Install jq
                  run: sudo apt-get install jq
            
                - name: Fetch public key
                  id: fetch_key
                  run: |
                    RESPONSE=$(curl -L \
                      -H "Accept: application/vnd.github+json" \
                      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "X-GitHub-Api-Version:  2022-11-28" \
                      https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
                    echo "$RESPONSE"
                    KEY=$(echo "$RESPONSE" | jq -r '.key')
                    echo "PUBLIC_KEY=$KEY" >> $GITHUB_ENV
            
                - name: Use public key
                  run: |
                    echo "The public key is: $PUBLIC_KEY"
                    # Your further steps that require the PUBLIC_KEY environment variable

